export const ar = {
  language: "العربيه",
  home: {
    welcome: 'مرحبًا',
    choose_language: 'اختر لغتك المفضلة',
    arabic: 'العربية',
    english: 'الإنجليزية',
    wishlist: "المفضلة",
    phoneInvalid:"رقم الهاتف غير صالح ",
    whatsappMsg:`مرحبًا،
أتواصل معك بخصوص طلب خدمة عبر تطبيق أسطا باشا.
وجدت خدمتك على التطبيق وأرغب في التواصل معك لمزيد من التفاصيل.
يرجى الرد في أقرب وقت`,
    noitems: "لا توجد عناصر  ",
    invalid_phone_number:"رقم الهاتف غير صالح",
    password_length_error:"كلمة المرور يجب أن تكون على الأقل 8 أحرف",
    editeProfile: 'تعديل الملف الشخصي',
    changePassword: 'تغيير كلمة المرور ',
    rateService: 'تقييم الخدمة',
    providersList: 'قائمة الحرفيين',
    language: "اللغة",
    country: "البلد",
    Notifications: "الإشعارات",
    usages: 'تعليمات الأستخدام',
    logout: 'تسجيل الخروج',

    settings: "الإعدادات",
    active: "متاح",
    inactive: "مشغول",
    technicalsupport: 'الدعم الفني',
    first_name: "الاسم الأول",
    last_name: "الاسم الأخير",
    email: "البريد الإلكتروني",
    whatsapp: "رقم الواتساب",
    add: "أضافة",
    addedSuccessfully: "تم الأضافة بنجاح!",
    profile: "الملف الشخصي",
    craftsman: "حرفي",
    client: "عميل",
    shop_owner: "صاحب محل",
    select_account_type: "من فضلك اختر نوع الحساب أولاً",
    choose_account_type: "اختر نوع الحساب للمتابعة",
    next: "التالي",
    choose_account_type: "اختر نوع الحساب للمتابعة",
    next: "التالي",
    user_instructions: 'تعليمات المستخدمين',
    cancel: 'الغاء',
    Users:"المستخدمين",
    yes: "نعم",
    select_country: 'اختر البلد',
    edit: "تعديل",
    providers: "مقدمي الخدمات",
    myRates: 'تقييماتي',
    craft_map: 'خريطة الحرفيين',
    nearest_providers: 'أقرب مقدمي الخدمة',
    loading_data: 'جاري تحميل البيانات...',
    phone_number: 'رقم الهاتف المحمول',
    password: 'كلمة المرور ',
    skip: 'تخطي',
    fill_all_fields: 'برجاء ملئ جميع البيانات',
    incorrect_password: 'كلمة المرور غير صحيحة',
    log: 'التسجيل',
    allAds:"الاعلانات",
    Pleasefilloutallfields:"يرجى ملء جميع الحقول",
    enter_verification_code: 'أدخل رمز التحقق',
    sent_code_to: 'لقد تلقيت رمز التحقيق علي الهاتف',
    resend_in: 'أعد إرسال الرمز خلال',
    resend_code: 'إعادة إرسال الرمز',
    verify: 'تحقق',
    enter_verification_code: 'أدخل رمز التحقق',
    sent_code_to: 'لقد تلقيت رمز التحقيق علي الهاتف',
    resend_in: 'أعد إرسال الرمز خلال',
    resend_code: 'إعادة إرسال الرمز',
    verify: 'تحقق',
    sendagain: "تم إرسال الرمز مرة أخرى",
    UseWhatsApp: " استخدم واتساب",
    Callbyphone: "الأتصال بالهاتف",
    Leaveyourcommenthere: "اترك تعليقك هنا",
    Send: "ارسال",
    search: "بحث",
    searchPlaceholder: "ابحث عن حرفي بالاسم او رقم الهاتف",
    passwordMatchError: "يجب أن تتطابق كلمات المرور",
    confirmPasswordLabel: "تأكيد كلمة المرور",
    passwordLengthHelper: "يجب أن تحتوي على 8 أحرف على الأقل",
    newPasswordLabel: "كلمة المرور الجديدة",
    currentPasswordHelper: "أدخل كلمة المرور الحالية لتأكيد التغيير",
    currentPasswordLabel: "كلمة المرور الحالية",
    resetPasswordHeader: "إعادة تعيين كلمة المرور",
    resetPasswordSubText: "يجب أن تكون كلمة المرور الجديدة مختلفة عن كلمة المرور المستخدمة مسبقًا",
    alertSuccessTitle: "نجاح",
    alertSuccessMessage: "تم تعيين كلمة المرور الجديدة بنجاح",
    alertErrorTitle: "خطأ",
    alertPasswordMismatchMessage: "يجب أن تتطابق كلمات المرور",
    alertCurrentPasswordMissingMessage: "يرجى إدخال كلمة المرور الحالية",
    am: "صباحا",
    pm: "مساءا",
    distance: "مسافة",

    shopOwner: "صاحب محل",
    first_name_placeholder: "الاسم الاول",
    last_name_placeholder: "الاسم الاخير",
    email_placeholder: "البريد الالكتروني",
    whatsapp_placeholder: "رقم الواتس اب",
    experience_years_placeholder: "عدد سنوات الخبرة",
    country_placeholder: "البلد",
    city_placeholder: "المدينة",
    lat_placeholder: "خط العرض",
    km:"كم",
    awayfromyou:"يبعد عنك",
    long_placeholder: "خط الطول",
    address_placeholder: "العنوان",
    subCategories_placeholder: "اختار التصنيف",
    experience_description_placeholder: "وصف المنتجات المقدمة",
    providerexperience_description_placeholder: "وصف الخدمات  المقدمة ",
    price_placeholder: "متوسط سعر الخدمة",
    card_number_placeholder: "رقم البطاقة الشخصية",
    card_image_placeholder: "صورة الهوية",
    shop_name_placeholder: "اسم المحل",

    chooseSubCategoryPlaceholder: "اختر التصنيف الفرعي",
    chooseCategoryPlaceholder: "اختر التصنيف الاساسي",
    chooseIdImageText: "اضافة صورة الهوية",
    certificatesText: "الشهادات",
    addcertificatesText: "اضافة شهادة جديدة ",
    forgetPassword: "هل نسيت كلمة مرور؟",
    forgetPasswordText: "نسيت كلمة مرور",
    shopImagesText: "صور المحل",
    workingHoursText: "أوقات العمل",
    workingHoursPlaceholder: "مواعيد العمل",
    addSuccessAlert: "تم الاضافة بنجاح!",
    editSuccessAlert: "تم التعديل بنجاح!",
    profileHeaderTitle: "الملف الشخصي",
    Sunday: "الأحد",
    Monday: "الاثنين",
    Tuesday: "الثلاثاء",
    Wednesday: "الأربعاء",
    Thursday: "الخميس",
    Friday: "الجمعة",
    Saturday: "السبت",
    phoneExamplePlaceholder: "مثال: 01012345678",
    fillAllFieldsAlert: "يرجى تعبئة جميع الحقول",
    addButtonText: "اضافة",
    countrySearchPlaceholder: "ابحث عن بلدك",
    addNewImageText: "إضافة صورة جديدة",
    addOrder: "أضف",
    from: "من",
    to: "الي",
    priceTitle: "السعر :",
    years: "سنوات",
    priceFrom: "ابتداءً من",
    serviceRatingHeader: "تقييم الخدمة",
    emptyItemsText: "لا توجد عناصر",
    leaveCommentLabel: "اترك تعليقك هنا",
    sendButtonText: "ارسال",
    currentStatusFreeTrial: "خدماتنا الآن مجاناً.. اغتنم الفرصة وجرّب بنفسك",
    currentStatusPackage: "في باقة {{packageTitle}}",
    startDateText: "سوف تبدأ يوم {{startDate}}",
    remainingContactsText: "ولديك {{times}} التواصل",
    clientsListTitle: "قائمة العملاء",
    noOrdersText: "لا توجد طلبات",
    enterDataModalText: "أدخل بياناتك لاستكمال الحساب",
    okButtonText: "حسناً",
    contactSupportText: "يرجي التوصل مع خدمة العملاء للاشتراك في باقة مناسبة",
    useWhatsAppText: "استخدم واتساب",
    clientLabel: "العميل:",
    phoneLabel: "الهاتف:",
    dateLabel: "التاريخ:",
    timeLabel: "الوقت:",
    showOffer: "عرض العرض",
    featuredServicesTitle: "خدمات مميزة",
    seeMoreText: "المزيد",
    Phonenumberisvalid:"Phone number is valid",
isValidPhoneNumber:"رقم الهاتف غير صالح",
    featuredShopsTitle: "المحلات المميزة",
    searchPlaceholder: "البحث بالاسم أو رقم الهاتف",
    similarItemsTitle: "العناصر المشابهة",
    comments: "التعليقات",
    otherCraftsmenTitle: "حرفيين أخريين",
    description: "الوصف",
    resetText: "إعادة ضبط",
    NoInternet:"لا يوجد أنترنت",
  checkinternet:"برجاء التأكد من الاتصال بالانترنت",
    searchText: "بحث",
    averageCostLabel: "متوسط تكلفة",
    searchFilterHeader: "فلترة البحث",
    categoriesLabel: "التصنيفات",
    subcategoriesLabel: "التصنيفات الفرعية",

    home: 'الرئيسية',
    map: 'الخريطة',
    wishlist: 'المفضلة',
    settings: 'الإعدادات',
    verify: "تحقق",
    resend_code: "إعادة إرسال الرمز",
    resend_code_timer: "أعد إرسال الرمز خلال {{time}}",
    enter_verification_code: "أدخل رمز التحقق",
    code_sent_to: "لقد تلقيت رمز التحقيق علي البريد الالكتروني",
    chooseDaysFirst: "برجاء اختيار أيام العمل أولا ",
    deleteTimes: "امسح المواعيد القديمة",
    save: "حفظ",
    login: "تسجيل الدخول",
    passValidation: "الرجاء إدخال كلمة مرور أكثر من 8 أرقام",
    verifyaccount: "تأكيد الحساب",
    verify: "تأكيد",
    unit: "للمتر",
    clickToUpload: "اضغط للتحميل",
    aboutus: "عن أسطا باشا",
    notaddedanyProviders: "لم تقم بإضافة حرفيين إلى قائمتك",
    Privacy: "سياسة الخصوصية",
welcomeStat:"مرحبًا بك في أسطا باشا – تطبيقك الأول لحل كل مشاكلك المنزلية بسهولة وأمان!",
passwordValidation:"كلمة المرور يجب أن تكون على الأقل 8 أحرف",
showAd:"عرض الاعلان",
showAll:"عرض الكل",
showDetails:"عرض التفاصيل",
addNewcraft:"يمكن اضافة حرفة جديدة"

  }
}