export const en = {
  language: "English",
  home: {
      welcome: 'Welcome',
  choose_language: 'Choose your preferred language',
  arabic: 'Arabic',
  english: 'English',
  invalid_phone_number:"Phone Number Invalid",
  password_length_error:"Password must be at least 8 characters",
  wishlist: "Wishlist",
  noitems: "There are no items",
      phoneInvalid:"phone Number Invalid ",
    whatsappMsg:`Hello,
I'm contacting you regarding a service request through the Osta Basha app.

I found your service on the app and would like to contact you for more details.

Please reply as soon as possible.`,
  editeProfile: 'Edit Profile',
  changePassword: 'Change Password',
  rateService: 'Rate service',
  providersList: 'Providers List',
  language: "Language",
  country: "Country",
  Notifications: "Notifications",
  usages: 'Instructions for use',
  logout: "Log out",
  settings: "Settings",
  active: "Active",
  inactive: "Inactive",
  technicalsupport: 'technical support',
      first_name: "First Name",
    last_name: "Last Name",
    email: "Email",
    whatsapp: "WhatsApp Number",
        add:"Add",
        addedSuccessfully:"Added successfully!",
          editSuccessAlert: "Edited successfully!",

                   profile: "Profile",
                       craftsman: "Provider",
    client: "Client",
    shop_owner: "Shop Owner",

    select_account_type: "Please select an account type first",


  choose_account_type: "Choose account type to continue",
  next: "Next",
  user_instructions: 'User Instructions',
cancel:'cancel',
yes:"yes",
  select_country: 'Select Country',
edit:"Edit",
providers:"providers",
myRates:'My Ratings',
  craft_map: 'Providers Map',
  nearest_providers: 'Nearest Service Providers',
  loading_data: 'Loading data...',
  fill_all_fields: 'Please fill in all fields',
  incorrect_password: 'Incorrect password',
  phone_number: 'Phone Number',
  password: 'Password',
  skip: 'Skip',
  log:'register',
  sendagain:"The code has been sent again",
  UseWhatsApp:"Use WhatsApp",
Callbyphone:"Call by phone",
Leaveyourcommenthere:"Leave your comment here",
Send:"Send",
search:"search",
searchPlaceholder:"Search by name or phone number",
  passwordMatchError: "Passwords must match",
  confirmPasswordLabel: "Confirm Password",
  passwordLengthHelper: "Must be at least 8 characters",
  newPasswordLabel: "New Password",
  currentPasswordHelper: "Enter current password to confirm changes",
  currentPasswordLabel: "Current Password",
  resetPasswordHeader: "Reset Password",
  resetPasswordSubText: "New password must be different from the previous one",
  alertSuccessTitle: "Success",
  alertSuccessMessage: "New password set successfully",
  alertErrorTitle: "Error",
  alertPasswordMismatchMessage: "Passwords must match",
  alertCurrentPasswordMissingMessage: "Please enter the current password",
  shopOwner:"Shop Owner",
    first_name_placeholder: "First Name",
  last_name_placeholder: "Last Name",
  email_placeholder: "Email",
  whatsapp_placeholder: "WhatsApp Number",
  experience_years_placeholder: "Years of Experience",
  country_placeholder: "Country",
  city_placeholder: "City",
  lat_placeholder: "Latitude",
  long_placeholder: "Longitude",
  address_placeholder: "Address",
  subCategories_placeholder: "Select Category",
  experience_description_placeholder: "Description of the products offered",
  price_placeholder: "Average Service Price",
      providerexperience_description_placeholder: "Description of services provided ",

  card_number_placeholder: "National ID Number",
  card_image_placeholder: "ID Card Image",
  shop_name_placeholder: "Shop Name",
  chooseSubCategoryPlaceholder: "Choose subcategory",
  chooseIdImageText: "Add ID image",
  certificatesText: "Certificates",
  shopImagesText: "Shop images",
  workingHoursText: "Working hours",
  workingHoursPlaceholder: "Working hours",
  addSuccessAlert: "Added successfully!",
  profileHeaderTitle: "Profile",
Sunday: "Sunday",
   Monday: "Monday",
   Tuesday: "Tuesday",
Wednesday: "Wednesday",
   Thursday: "Thursday", 
  Friday: "Friday",
   Saturday: "Saturday",
  addcertificatesText: "Add new certificate",

  phoneExamplePlaceholder: "Example: 01012345678",
  fillAllFieldsAlert: "Please fill all fields",
  addButtonText: "Add",
  countrySearchPlaceholder: "Search your country",
  addNewImageText: "Add new image",

addOrder:"Add",
from:"From",
to:"To",
  priceTitle: "Price:",
  priceFrom: "Starting from",
  serviceRatingHeader: "Service Rating",
  emptyItemsText: "No items available",
  leaveCommentLabel: "Leave your comment here",
  sendButtonText: "Send",
  currentStatusFreeTrial: "Our services are now free. Seize the opportunity and try it yourself.",
  currentStatusPackage: "In the package {{packageTitle}}",
  startDateText: "Will start on {{startDate}}",
  remainingContactsText: "You have {{times}} contacts remaining",
  clientsListTitle: "Clients List",
  noOrdersText: "No orders",
  enterDataModalText: "Enter your data to complete the account",
  okButtonText: "OK",
  contactSupportText: "Please contact customer service to subscribe to a suitable package",
  useWhatsAppText: "Use WhatsApp",
  clientLabel: "Client:",
  phoneLabel: "Phone:",
  dateLabel: "Date:",
  timeLabel: "Time:",
    showOffer: "View Offer",
  featuredServicesTitle: "Featured Services",
  seeMoreText: "See More",
  featuredShopsTitle: "Featured Shops",
searchPlaceholder:"Search by name or phone number",
  similarItemsTitle: "Similar Items",
  comments: "Comments",
  otherCraftsmenTitle: "Other Craftsmen",
description:"description",
  years:"years",
    resetText: "Reset",
  searchText: "Search",
  averageCostLabel: "Average Cost",
  categoriesLabel: "Categories",
  searchFilterHeader: "Search Filter",
  subcategoriesLabel: "Subcategories",
    home: 'Home',
    map: 'Map',
    wishlist: 'Wishlist',
    settings: 'Settings',
  verify: "Verify",
  resend_code: "Resend Code",
    NoInternet:"No Internet",
  checkinternet:"Please check your internet connection",
isValidPhoneNumber:"Phone number is valid",

  resend_code_timer: "You can resend the code in {{time}}",
  enter_verification_code: "Enter the verification code",
  code_sent_to: "You have received the code on this email",
  am:"AM",
pm:"PM",
  chooseDaysFirst:"Please choose days of working first",
    deleteTimes:"Delete old appointments",
      save:"Save",
        login:"Login",
          passValidation:"please enter password more than 8 numbers",
            verifyaccount:"Verify Account",
              forgetPassword: "Forgot Password?",
                forgetPasswordText: "Forgot Password",
  verify:"Verify",
    unit:"Per (m)",
    km:"KM",
    awayfromyou:"away from you",
    distance: "Distance",
showDetails:"show Details",
addNewcraft:"A new craft can be added",
    Users:"Users",


clickToUpload:"Click to upload",
aboutus:"About us",
notaddedanyProviders:"You have not added any craftsmen to your list.",
Privacy:"Privacy Policy",
welcomeStat:"Welcome to Asta Pasha – your number one app to solve all your household problems easily and safely!",
    allAds:"Ads",
        Pleasefilloutallfields:"Please fill out all fields",
        passwordValidation:"Password must be at least 8 characters long.",
        showAd:"Show ad",
showAll:"Show all",
    chooseCategoryPlaceholder: "Choose Category",



















}}